@host = http://localhost:8000
@users = /api/users

GET {{host}}/health

###

GET {{host}}{{users}}/

###

GET {{host}}{{users}}/kr79yajnv1c7unqtqhi0j5ds

###

POST {{host}}{{users}}
Content-Type: application/json

{
  "name": "Ducc",
  "email": "sfdds@example.com",
  "role": "admin",
  "is_active": true
}

###

DELETE {{host}}{{users}}/zlglnroc0f4dpjy8tmry22xf