@host = http://localhost:8000
@auth = /api/v1/auth

POST {{host}}{{auth}}/
Content-Type: application/json

{
  "first_name": "Register",
  "last_name": "Test",
  "apu_id": "TP022312",
  "role": "student",
  "email": "register_user@example.com",
  "password": "registerPassword",
  "is_active": true
}

###

POST {{host}}{{auth}}/token
Content-Type: application/x-www-form-urlencoded

username=register_user@example.com&password=registerPassword

###

POST {{host}}{{auth}}/refresh
Content-Type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InhlNzNoOGF3YWRnbTAxODZveHpkaGZkaCIsInN1YiI6InJlZ2lzdGVyX3VzZXJAZXhhbXBsZS5jb20iLCJpbnN0aXR1dGlvbmFsX2lkIjoiVFAwMjIzMTIiLCJ0eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDg3OTc0M30.R3hsE321fYO_shoGMUajsP58OPo4ipY6GVci-XrJuIY"
}