"""add cascade delete

Revision ID: 15e5c5749dda
Revises: 606321adfa01
Create Date: 2026-01-17 17:48:12.316892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '15e5c5749dda'
down_revision: Union[str, Sequence[str], None] = '606321adfa01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_repositories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('github_repositories_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('github_repository_framework_links', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('github_repository_framework_links_repository_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'github_repositories', ['repository_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('github_repository_programming_language_links', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('github_repository_programming_language_links_repository_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'github_repositories', ['repository_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('refresh_tokens_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_framework_links', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_framework_links_framework_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_framework_links_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'frameworks', ['framework_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_programming_language_links', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_programming_language_links_programming_language_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_programming_language_links_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'programming_languages', ['programming_language_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_programming_language_links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_programming_language_links_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('user_programming_language_links_programming_language_id_fkey'), 'programming_languages', ['programming_language_id'], ['id'])

    with op.batch_alter_table('user_framework_links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_framework_links_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('user_framework_links_framework_id_fkey'), 'frameworks', ['framework_id'], ['id'])

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('refresh_tokens_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('github_repository_programming_language_links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('github_repository_programming_language_links_repository_id_fkey'), 'github_repositories', ['repository_id'], ['id'])

    with op.batch_alter_table('github_repository_framework_links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('github_repository_framework_links_repository_id_fkey'), 'github_repositories', ['repository_id'], ['id'])

    with op.batch_alter_table('github_repositories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('github_repositories_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
