"""add skills to github repository

Revision ID: 47556753776c
Revises: 0e74bf4991f2
Create Date: 2026-01-03 19:38:41.398152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47556753776c'
down_revision: Union[str, Sequence[str], None] = '0e74bf4991f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_repositories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_repositories', schema=None) as batch_op:
        batch_op.drop_column('skills')

    # ### end Alembic commands ###
