"""add repository statistics columns

Revision ID: 606321adfa01
Revises: e740dd09ff75
Create Date: 2026-01-05 18:16:20.771517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '606321adfa01'
down_revision: Union[str, Sequence[str], None] = 'e740dd09ff75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_repositories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repository_language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
        batch_op.add_column(sa.Column('topics', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('forks_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stargazers_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subscribers_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('open_issues_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_repositories', schema=None) as batch_op:
        batch_op.drop_column('open_issues_count')
        batch_op.drop_column('subscribers_count')
        batch_op.drop_column('stargazers_count')
        batch_op.drop_column('forks_count')
        batch_op.drop_column('topics')
        batch_op.drop_column('repository_language')

    # ### end Alembic commands ###
