"""add skills tables

Revision ID: 6065e4ff9fd4
Revises: 47556753776c
Create Date: 2026-01-04 19:28:01.785244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6065e4ff9fd4'
down_revision: Union[str, Sequence[str], None] = '47556753776c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frameworks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('added_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('frameworks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frameworks_name'), ['name'], unique=True)

    op.create_table('programming_languages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('added_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('programming_languages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programming_languages_name'), ['name'], unique=True)

    op.create_table('user_framework_links',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('framework_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'framework_id')
    )
    op.create_table('user_programming_language_links',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('programming_language_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['programming_language_id'], ['programming_languages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'programming_language_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_programming_language_links')
    op.drop_table('user_framework_links')
    with op.batch_alter_table('programming_languages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programming_languages_name'))

    op.drop_table('programming_languages')
    with op.batch_alter_table('frameworks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frameworks_name'))

    op.drop_table('frameworks')
    # ### end Alembic commands ###
