"""add unique constraint to github repository url

Revision ID: 8d00ff9cf22c
Revises: 3c69d8b16eb1
Create Date: 2025-12-28 19:14:32.851179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d00ff9cf22c'
down_revision: Union[str, Sequence[str], None] = '3c69d8b16eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_repositories', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['url'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_repositories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
