"""github_repository: user_id and name unique constraint

Revision ID: d3d0249281d9
Revises: 8d00ff9cf22c
Create Date: 2025-12-30 18:16:13.010033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd3d0249281d9'
down_revision: Union[str, Sequence[str], None] = '8d00ff9cf22c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_repositories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
        batch_op.add_column(sa.Column('collaborators', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('contributors', sa.JSON(), nullable=True))
        batch_op.create_unique_constraint('uix_user_id_name', ['user_id', 'name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_repositories', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_id_name', type_='unique')
        batch_op.drop_column('contributors')
        batch_op.drop_column('collaborators')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
