"""add skill links to github table

Revision ID: e740dd09ff75
Revises: 6065e4ff9fd4
Create Date: 2026-01-04 22:02:28.198890

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e740dd09ff75"
down_revision: Union[str, Sequence[str], None] = "6065e4ff9fd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_repository_framework_links",
        sa.Column("repository_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("framework_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["framework_id"],
            ["frameworks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["github_repositories.id"],
        ),
        sa.PrimaryKeyConstraint("repository_id", "framework_id"),
    )

    op.create_table(
        "github_repository_programming_language_links",
        sa.Column("repository_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "programming_language_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["programming_language_id"],
            ["programming_languages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["github_repositories.id"],
        ),
        sa.PrimaryKeyConstraint("repository_id", "programming_language_id"),
    )
    with op.batch_alter_table("github_repositories", schema=None) as batch_op:
        batch_op.drop_column("skills")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("github_repositories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "skills",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )

    op.drop_table("github_repository_programming_language_links")
    op.drop_table("github_repository_framework_links")
    # ### end Alembic commands ###
